#!/usr/bin/env python3
"""
Custom Configuration Builder for RustDesk

This script generates the custom_config.rs file with values from environment
variables or command-line arguments, enabling CI/CD injection of server settings.
"""

import os
import sys
import argparse
from pathlib import Path

def get_env_var(name: str, default: str = "") -> str:
    """Get environment variable with fallback"""
    return os.environ.get(name, default)

def generate_config_rs(key: str, api_server: str, relay_server: str, rendezvous_server: str) -> str:
    """Generate the custom_config.rs file content"""

    # Escape strings for Rust
    def escape_str(s: str) -> str:
        return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r')

    # Use raw string to avoid f-string issues with double braces
    content = f"""//! Custom Server Configuration (Generated)
//!
//! This file is automatically generated during build.
//! DO NOT EDIT MANUALLY - changes will be overwritten.
//!
//! Generated with:
//! - Key: {'***' if key else 'Not set'}
//! - API Server: {api_server or 'Not set'}
//! - Relay Server: {relay_server or 'Not set'}
//! - Rendezvous Server: {rendezvous_server or 'Not set'}

use hbb_common::config::Config;
use hbb_common::log;

/// Build-time injected configuration
pub struct BuildConfig {{
    pub key: &'static str,
    pub api_server: &'static str,
    pub relay_server: &'static str,
    pub custom_rendezvous_server: &'static str,
}}

/// Configuration injected at build time
const BUILD_CONFIG: BuildConfig = BuildConfig {{
    key: "{escape_str(key)}",
    api_server: "{escape_str(api_server)}",
    relay_server: "{escape_str(relay_server)}",
    custom_rendezvous_server: "{escape_str(rendezvous_server)}",
}};

/// Apply the build-time configuration
///
/// This should be called early in the application startup
pub fn apply_build_config() {{
    let config = &BUILD_CONFIG;

    if !config.key.is_empty() {{
        Config::set_option("key".to_string(), config.key.to_string());
        log::info!("Applied build-time client key");
    }}
    if !config.api_server.is_empty() {{
        Config::set_option("api-server".to_string(), config.api_server.to_string());
        log::info!("Applied build-time API server: {{}}", config.api_server);
    }}
    if !config.relay_server.is_empty() {{
        Config::set_option("relay-server".to_string(), config.relay_server.to_string());
        log::info!("Applied build-time relay server: {{}}", config.relay_server);
    }}
    if !config.custom_rendezvous_server.is_empty() {{
        Config::set_option("custom-rendezvous-server".to_string(), config.custom_rendezvous_server.to_string());
        log::info!("Applied build-time rendezvous server: {{}}", config.custom_rendezvous_server);
    }}
}}

/// Get the build configuration
pub fn get_build_config() -> &'static BuildConfig {{
    &BUILD_CONFIG
}}

/// Helper function to check if custom configuration is available
pub fn has_custom_config() -> bool {{
    let config = &BUILD_CONFIG;
    !config.key.is_empty() && !config.custom_rendezvous_server.is_empty()
}}

/// Get current effective configuration
/// Returns: (key, api_server, relay_server, custom_rendezvous_server)
pub fn get_effective_config() -> (String, String, String, String) {{
    let config = &BUILD_CONFIG;

    // Use build config if available, otherwise fall back to runtime config
    let key = if !config.key.is_empty() {{
        config.key.to_string()
    }} else {{
        Config::get_option("key")
    }};

    let api_server = if !config.api_server.is_empty() {{
        config.api_server.to_string()
    }} else {{
        Config::get_option("api-server")
    }};

    let relay_server = if !config.relay_server.is_empty() {{
        config.relay_server.to_string()
    }} else {{
        Config::get_option("relay-server")
    }};

    let custom_rendezvous_server = if !config.custom_rendezvous_server.is_empty() {{
        config.custom_rendezvous_server.to_string()
    }} else {{
        Config::get_option("custom-rendezvous-server")
    }};

    (key, api_server, relay_server, custom_rendezvous_server)
}}

/// Print configuration for debugging
pub fn print_config() {{
    let config = &BUILD_CONFIG;
    println!("=== Custom Server Configuration ===");
    println!("Key: {{}}", if config.key.is_empty() {{ "Not set" }} else {{ "***" }});
    println!("API Server: {{}}", if config.api_server.is_empty() {{ "Not set" }} else {{ config.api_server }});
    println!("Relay Server: {{}}", if config.relay_server.is_empty() {{ "Not set" }} else {{ config.relay_server }});
    println!("Rendezvous Server: {{}}", if config.custom_rendezvous_server.is_empty() {{ "Not set" }} else {{ config.custom_rendezvous_server }});
    println!("===================================");
}}

/// Check if configuration is valid for production use
pub fn is_valid() -> bool {{
    let config = &BUILD_CONFIG;
    !config.key.is_empty() && !config.custom_rendezvous_server.is_empty()
}}

/// Get configuration summary for logging
pub fn get_config_summary() -> String {{
    let config = &BUILD_CONFIG;
    format!(
        "CustomConfig{{key: {{}}, api: {{}}, relay: {{}}, rendezvous: {{}}}}",
        if config.key.is_empty() {{ "none" }} else {{ "set" }},
        if config.api_server.is_empty() {{ "default" }} else {{ config.api_server }},
        if config.relay_server.is_empty() {{ "default" }} else {{ config.relay_server }},
        if config.custom_rendezvous_server.is_empty() {{ "none" }} else {{ config.custom_rendezvous_server }}
    )
}}
"""
    return content

def main():
    parser = argparse.ArgumentParser(description='Generate custom configuration for RustDesk')
    parser.add_argument('--key', help='Client authentication key')
    parser.add_argument('--api-server', help='API server URL')
    parser.add_argument('--relay-server', help='Relay server URL')
    parser.add_argument('--rendezvous-server', help='Rendezvous server hostname')
    parser.add_argument('--output', default='src/custom_config.rs', help='Output file path')
    parser.add_argument('--env-prefix', default='CUSTOM_', help='Environment variable prefix')

    args = parser.parse_args()

    # Get values from environment variables (with command-line override)
    env_prefix = args.env_prefix
    key = args.key or get_env_var(f'{env_prefix}CLIENT_KEY', '')
    api_server = args.api_server or get_env_var(f'{env_prefix}API_SERVER', '')
    relay_server = args.relay_server or get_env_var(f'{env_prefix}RELAY_SERVER', '')
    rendezvous_server = args.rendezvous_server or get_env_var(f'{env_prefix}RENDEZVOUS_SERVER', '')

    # Validate required fields
    if not key:
        print("Warning: No client key provided. Set CUSTOM_CLIENT_KEY environment variable or use --key")
    if not rendezvous_server:
        print("Error: Rendezvous server is required. Set CUSTOM_RENDEZVOUS_SERVER environment variable or use --rendezvous-server")
        sys.exit(1)

    # Generate configuration
    config_content = generate_config_rs(key, api_server, relay_server, rendezvous_server)

    # Write to file
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w') as f:
        f.write(config_content)

    print(f"✅ Generated custom configuration: {output_path}")
    print(f"   Rendezvous: {rendezvous_server}")
    print(f"   API: {api_server or 'default'}")
    print(f"   Relay: {relay_server or 'default'}")
    print(f"   Key: {'***' if key else 'Not set'}")

    # Also generate a summary file
    summary_path = output_path.parent / "custom_config_summary.txt"
    with open(summary_path, 'w') as f:
        f.write(f"Custom RustDesk Configuration\n")
        f.write(f"=============================\n")
        f.write(f"Generated: {os.environ.get('BUILD_TIMESTAMP', 'unknown')}\n")
        f.write(f"Rendezvous Server: {rendezvous_server}\n")
        f.write(f"API Server: {api_server or 'default'}\n")
        f.write(f"Relay Server: {relay_server or 'default'}\n")
        f.write(f"Client Key: {'configured' if key else 'not set'}\n")

    print(f"✅ Generated summary: {summary_path}")

if __name__ == '__main__':
    main()