//! Build script for custom configuration injection
//!
//! This script generates the custom_config.rs file with values from environment variables.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Read environment variables for custom configuration
    let key = env::var("CUSTOM_CLIENT_KEY").unwrap_or_default();
    let api_server = env::var("CUSTOM_API_SERVER").unwrap_or_default();
    let relay_server = env::var("CUSTOM_RELAY_SERVER").unwrap_or_default();
    let rendezvous_server = env::var("CUSTOM_RENDEZVOUS_SERVER").unwrap_or_default();

    // Generate the custom_config.rs file
    let config_content = format!(
        r#"//! Custom Server Configuration (Generated)
//!
//! This file is automatically generated during build.
//! DO NOT EDIT MANUALLY - changes will be overwritten.

use hbb_common::config::Config;

/// Build-time injected configuration
pub struct BuildConfig {{
    pub key: &'static str,
    pub api_server: &'static str,
    pub relay_server: &'static str,
    pub custom_rendezvous_server: &'static str,
}}

/// Configuration injected at build time
const BUILD_CONFIG: BuildConfig = BuildConfig {{
    key: "{}",
    api_server: "{}",
    relay_server: "{}",
    custom_rendezvous_server: "{}",
}};

/// Apply the build-time configuration
pub fn apply_build_config() {{
    let config = &BUILD_CONFIG;

    if !config.key.is_empty() {{
        Config::set_option("key".to_string(), config.key.to_string());
    }}
    if !config.api_server.is_empty() {{
        Config::set_option("api-server".to_string(), config.api_server.to_string());
    }}
    if !config.relay_server.is_empty() {{
        Config::set_option("relay-server".to_string(), config.relay_server.to_string());
    }}
    if !config.custom_rendezvous_server.is_empty() {{
        Config::set_option("custom-rendezvous-server".to_string(), config.custom_rendezvous_server.to_string());
    }}
}}

/// Get the build configuration
pub fn get_build_config() -> &'static BuildConfig {{
    &BUILD_CONFIG
}}

/// Helper function to check if custom configuration is available
pub fn has_custom_config() -> bool {{
    let config = &BUILD_CONFIG;
    !config.key.is_empty() && !config.custom_rendezvous_server.is_empty()
}}

/// Get current effective configuration
pub fn get_effective_config() -> (String, String, String, String) {{
    let config = &BUILD_CONFIG;

    // Use build config if available, otherwise fall back to runtime config
    let key = if !config.key.is_empty() {{
        config.key.to_string()
    }} else {{
        Config::get_option("key")
    }};

    let api_server = if !config.api_server.is_empty() {{
        config.api_server.to_string()
    }} else {{
        Config::get_option("api-server")
    }};

    let relay_server = if !config.relay_server.is_empty() {{
        config.relay_server.to_string()
    }} else {{
        Config::get_option("relay-server")
    }};

    let custom_rendezvous_server = if !config.custom_rendezvous_server.is_empty() {{
        config.custom_rendezvous_server.to_string()
    }} else {{
        Config::get_option("custom-rendezvous-server")
    }};

    (key, api_server, relay_server, custom_rendezvous_server)
}}

/// Print configuration for debugging
pub fn print_config() {{
    let config = &BUILD_CONFIG;
    println!("=== Custom Server Configuration ===");
    println!("Key: {}", if config.key.is_empty() {{ "Not set" }} else {{ "***" }});
    println!("API Server: {}", if config.api_server.is_empty() {{ "Not set" }} else {{ config.api_server }});
    println!("Relay Server: {}", if config.relay_server.is_empty() {{ "Not set" }} else {{ config.relay_server }});
    println!("Rendezvous Server: {}", if config.custom_rendezvous_server.is_empty() {{ "Not set" }} else {{ config.custom_rendezvous_server }});
    println!("===================================");
}}
"#,
        escape_string(&key),
        escape_string(&api_server),
        escape_string(&relay_server),
        escape_string(&rendezvous_server)
    );

    // Write to src/custom_config.rs
    let out_dir = env::var("OUT_DIR").unwrap_or_else(|_| "src".to_string());
    let dest_path = Path::new(&out_dir).join("custom_config.rs");

    fs::write(&dest_path, config_content).expect("Failed to write custom_config.rs");

    println!("cargo:rerun-if-env-changed=CUSTOM_CLIENT_KEY");
    println!("cargo:rerun-if-env-changed=CUSTOM_API_SERVER");
    println!("cargo:rerun-if-env-changed=CUSTOM_RELAY_SERVER");
    println!("cargo:rerun-if-env-changed=CUSTOM_RENDEZVOUS_SERVER");

    println!("Generated custom configuration at: {:?}", dest_path);
}

fn escape_string(s: &str) -> String {
    s.replace('\\', "\\\\")
     .replace('"', "\\\"")
     .replace('\n', "\\n")
     .replace('\r', "\\r")
     .replace('\t', "\\t")
}