#[cfg(windows)]
fn build_windows() {
    let file = "src/platform/windows.cc";
    let file2 = "src/platform/windows_delete_test_cert.cc";
    cc::Build::new().file(file).file(file2).compile("windows");
    println!("cargo:rustc-link-lib=WtsApi32");
    println!("cargo:rerun-if-changed={}", file);
    println!("cargo:rerun-if-changed={}", file2);
}

#[cfg(target_os = "macos")]
fn build_mac() {
    let file = "src/platform/macos.mm";
    let mut b = cc::Build::new();
    if let Ok(os_version::OsVersion::MacOS(v)) = os_version::detect() {
        let v = v.version;
        if v.contains("10.14") {
            b.flag("-DNO_InputMonitoringAuthStatus=1");
        }
    }
    b.flag("-std=c++17").file(file).compile("macos");
    println!("cargo:rerun-if-changed={}", file);
}

#[cfg(all(windows, feature = "inline"))]
fn build_manifest() {
    use std::io::Write;
    if std::env::var("PROFILE").unwrap() == "release" {
        let mut res = winres::WindowsResource::new();
        res.set_icon("res/icon.ico")
            .set_language(winapi::um::winnt::MAKELANGID(
                winapi::um::winnt::LANG_ENGLISH,
                winapi::um::winnt::SUBLANG_ENGLISH_US,
            ))
            .set_manifest_file("res/manifest.xml");
        match res.compile() {
            Err(e) => {
                write!(std::io::stderr(), "{}", e).unwrap();
                std::process::exit(1);
            }
            Ok(_) => {}
        }
    }
}

fn install_android_deps() {
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap();
    if target_os != "android" {
        return;
    }
    let mut target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap();
    if target_arch == "x86_64" {
        target_arch = "x64".to_owned();
    } else if target_arch == "x86" {
        target_arch = "x86".to_owned();
    } else if target_arch == "aarch64" {
        target_arch = "arm64".to_owned();
    } else {
        target_arch = "arm".to_owned();
    }
    let target = format!("{}-android", target_arch);
    let vcpkg_root = std::env::var("VCPKG_ROOT").unwrap();
    let mut path: std::path::PathBuf = vcpkg_root.into();
    if let Ok(vcpkg_root) = std::env::var("VCPKG_INSTALLED_ROOT") {
        path = vcpkg_root.into();
    } else {
        path.push("installed");
    }
    path.push(target);
    println!(
        "cargo:rustc-link-search={}",
        path.join("lib").to_str().unwrap()
    );
    println!("cargo:rustc-link-lib=ndk_compat");
    println!("cargo:rustc-link-lib=oboe");
    println!("cargo:rustc-link-lib=c++");
    println!("cargo:rustc-link-lib=OpenSLES");
}

fn generate_custom_config() {
    // Generate custom configuration from environment variables
    let key = std::env::var("CUSTOM_CLIENT_KEY").unwrap_or_default();
    let api_server = std::env::var("CUSTOM_API_SERVER").unwrap_or_default();
    let relay_server = std::env::var("CUSTOM_RELAY_SERVER").unwrap_or_default();
    let rendezvous_server = std::env::var("CUSTOM_RENDEZVOUS_SERVER").unwrap_or_default();

    // Only generate if we have at least rendezvous server
    if !rendezvous_server.is_empty() {
        use std::fs;
        use std::path::Path;

        let content = format!(
            r#"//! Custom Server Configuration (Generated)
//!
//! This file is automatically generated during build.
//! DO NOT EDIT MANUALLY - changes will be overwritten.

use hbb_common::config::Config;

/// Build-time injected configuration
pub struct BuildConfig {{
    pub key: &'static str,
    pub api_server: &'static str,
    pub relay_server: &'static str,
    pub custom_rendezvous_server: &'static str,
}}

/// Configuration injected at build time
const BUILD_CONFIG: BuildConfig = BuildConfig {{
    key: "{}",
    api_server: "{}",
    relay_server: "{}",
    custom_rendezvous_server: "{}",
}};

/// Apply the build-time configuration
pub fn apply_build_config() {{
    let config = &BUILD_CONFIG;

    if !config.key.is_empty() {{
        Config::set_option("key".to_string(), config.key.to_string());
    }}
    if !config.api_server.is_empty() {{
        Config::set_option("api-server".to_string(), config.api_server.to_string());
    }}
    if !config.relay_server.is_empty() {{
        Config::set_option("relay-server".to_string(), config.relay_server.to_string());
    }}
    if !config.custom_rendezvous_server.is_empty() {{
        Config::set_option("custom-rendezvous-server".to_string(), config.custom_rendezvous_server.to_string());
    }}
}}

/// Get the build configuration
pub fn get_build_config() -> &'static BuildConfig {{
    &BUILD_CONFIG
}}

/// Check if custom configuration is available
pub fn has_custom_config() -> bool {{
    let config = &BUILD_CONFIG;
    !config.key.is_empty() && !config.custom_rendezvous_server.is_empty()
}}

/// Get effective configuration
pub fn get_effective_config() -> (String, String, String, String) {{
    let config = &BUILD_CONFIG;
    let key = if !config.key.is_empty() {{ config.key.to_string() }} else {{ Config::get_option("key") }};
    let api_server = if !config.api_server.is_empty() {{ config.api_server.to_string() }} else {{ Config::get_option("api-server") }};
    let relay_server = if !config.relay_server.is_empty() {{ config.relay_server.to_string() }} else {{ Config::get_option("relay-server") }};
    let custom_rendezvous_server = if !config.custom_rendezvous_server.is_empty() {{ config.custom_rendezvous_server.to_string() }} else {{ Config::get_option("custom-rendezvous-server") }};
    (key, api_server, relay_server, custom_rendezvous_server)
}}
"#,
            key.replace('\\', "\\\\").replace('"', "\\\""),
            api_server.replace('\\', "\\\\").replace('"', "\\\""),
            relay_server.replace('\\', "\\\\").replace('"', "\\\""),
            rendezvous_server.replace('\\', "\\\\").replace('"', "\\\"")
        );

        let dest_path = Path::new("src").join("custom_config.rs");
        fs::write(&dest_path, content).expect("Failed to write custom_config.rs");

        println!("cargo:rerun-if-env-changed=CUSTOM_CLIENT_KEY");
        println!("cargo:rerun-if-env-changed=CUSTOM_API_SERVER");
        println!("cargo:rerun-if-env-changed=CUSTOM_RELAY_SERVER");
        println!("cargo:rerun-if-env-changed=CUSTOM_RENDEZVOUS_SERVER");
    } else {
        // Generate default empty config
        let content = r#"//! Custom Server Configuration (Default)
//!
//! No custom configuration provided at build time.

use hbb_common::config::Config;

pub struct BuildConfig {
    pub key: &'static str,
    pub api_server: &'static str,
    pub relay_server: &'static str,
    pub custom_rendezvous_server: &'static str,
}

const BUILD_CONFIG: BuildConfig = BuildConfig {
    key: "",
    api_server: "",
    relay_server: "",
    custom_rendezvous_server: "",
};

pub fn apply_build_config() {
    // No build-time configuration to apply
}

pub fn get_build_config() -> &'static BuildConfig {
    &BUILD_CONFIG
}

pub fn has_custom_config() -> bool {
    false
}

pub fn get_effective_config() -> (String, String, String, String) {
    (
        Config::get_option("key"),
        Config::get_option("api-server"),
        Config::get_option("relay-server"),
        Config::get_option("custom-rendezvous-server")
    )
}
"#;

        let dest_path = Path::new("src").join("custom_config.rs");
        fs::write(&dest_path, content).expect("Failed to write default custom_config.rs");
    }
}

fn main() {
    hbb_common::gen_version();
    install_android_deps();

    // Generate custom configuration
    generate_custom_config();

    #[cfg(all(windows, feature = "inline"))]
    build_manifest();
    #[cfg(windows)]
    build_windows();
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap();
    if target_os == "macos" {
        #[cfg(target_os = "macos")]
        build_mac();
        println!("cargo:rustc-link-lib=framework=ApplicationServices");
    }
    println!("cargo:rerun-if-changed=build.rs");
}
