//! Custom Server Configuration (Generated)
//!
//! This file is automatically generated during build.
//! DO NOT EDIT MANUALLY - changes will be overwritten.
//!
//! Generated with:
//! - Key: ***
//! - API Server: https://api.test.example.com
//! - Relay Server: https://relay.test.example.com
//! - Rendezvous Server: test.example.com

use hbb_common::config::Config;
use hbb_common::log;

/// Build-time injected configuration
pub struct BuildConfig {
    pub key: &'static str,
    pub api_server: &'static str,
    pub relay_server: &'static str,
    pub custom_rendezvous_server: &'static str,
}

/// Configuration injected at build time
const BUILD_CONFIG: BuildConfig = BuildConfig {
    key: "test-key-123",
    api_server: "https://api.test.example.com",
    relay_server: "https://relay.test.example.com",
    custom_rendezvous_server: "test.example.com",
};

/// Apply the build-time configuration
///
/// This should be called early in the application startup
pub fn apply_build_config() {
    let config = &BUILD_CONFIG;

    if !config.key.is_empty() {
        Config::set_option("key".to_string(), config.key.to_string());
        log::info!("Applied build-time client key");
    }
    if !config.api_server.is_empty() {
        Config::set_option("api-server".to_string(), config.api_server.to_string());
        log::info!("Applied build-time API server: {}", config.api_server);
    }
    if !config.relay_server.is_empty() {
        Config::set_option("relay-server".to_string(), config.relay_server.to_string());
        log::info!("Applied build-time relay server: {}", config.relay_server);
    }
    if !config.custom_rendezvous_server.is_empty() {
        Config::set_option("custom-rendezvous-server".to_string(), config.custom_rendezvous_server.to_string());
        log::info!("Applied build-time rendezvous server: {}", config.custom_rendezvous_server);
    }
}

/// Get the build configuration
pub fn get_build_config() -> &'static BuildConfig {
    &BUILD_CONFIG
}

/// Helper function to check if custom configuration is available
pub fn has_custom_config() -> bool {
    let config = &BUILD_CONFIG;
    !config.key.is_empty() && !config.custom_rendezvous_server.is_empty()
}

/// Get current effective configuration
/// Returns: (key, api_server, relay_server, custom_rendezvous_server)
pub fn get_effective_config() -> (String, String, String, String) {
    let config = &BUILD_CONFIG;

    // Use build config if available, otherwise fall back to runtime config
    let key = if !config.key.is_empty() {
        config.key.to_string()
    } else {
        Config::get_option("key")
    };

    let api_server = if !config.api_server.is_empty() {
        config.api_server.to_string()
    } else {
        Config::get_option("api-server")
    };

    let relay_server = if !config.relay_server.is_empty() {
        config.relay_server.to_string()
    } else {
        Config::get_option("relay-server")
    };

    let custom_rendezvous_server = if !config.custom_rendezvous_server.is_empty() {
        config.custom_rendezvous_server.to_string()
    } else {
        Config::get_option("custom-rendezvous-server")
    };

    (key, api_server, relay_server, custom_rendezvous_server)
}

/// Print configuration for debugging
pub fn print_config() {
    let config = &BUILD_CONFIG;
    println!("=== Custom Server Configuration ===");
    println!("Key: {}", if config.key.is_empty() { "Not set" } else { "***" });
    println!("API Server: {}", if config.api_server.is_empty() { "Not set" } else { config.api_server });
    println!("Relay Server: {}", if config.relay_server.is_empty() { "Not set" } else { config.relay_server });
    println!("Rendezvous Server: {}", if config.custom_rendezvous_server.is_empty() { "Not set" } else { config.custom_rendezvous_server });
    println!("===================================");
}

/// Check if configuration is valid for production use
pub fn is_valid() -> bool {
    let config = &BUILD_CONFIG;
    !config.key.is_empty() && !config.custom_rendezvous_server.is_empty()
}

/// Get configuration summary for logging
pub fn get_config_summary() -> String {
    let config = &BUILD_CONFIG;
    format!(
        "CustomConfig{key: {}, api: {}, relay: {}, rendezvous: {}}",
        if config.key.is_empty() { "none" } else { "set" },
        if config.api_server.is_empty() { "default" } else { config.api_server },
        if config.relay_server.is_empty() { "default" } else { config.relay_server },
        if config.custom_rendezvous_server.is_empty() { "none" } else { config.custom_rendezvous_server }
    )
}
