name: Auto Update and Build

on:
  schedule:
    - cron: '0 0 2 * *'  # 每月2号00:00 UTC触发
  workflow_dispatch:  # 允许手动触发

env:
  SCITER_RUST_VERSION: "1.75"
  RUST_VERSION: "1.75"
  MAC_RUST_VERSION: "1.81"
  CARGO_NDK_VERSION: "3.1.2"
  SCITER_ARMV7_CMAKE_VERSION: "3.29.7"
  SCITER_NASM_DEBVERSION: "2.14-1"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  ANDROID_FLUTTER_VERSION: "3.24.5"
  FLUTTER_ELINUX_VERSION: "3.16.9"
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "6f29f12e82a8293156836ad81cc9bf5af41fe836"
  VERSION: "1.3.9"
  NDK_VERSION: "r27c"

jobs:
  update-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch and merge upstream
        run: |
          git remote add upstream https://github.com/rustdesk/rustdesk.git
          git fetch upstream
          git merge upstream/master --no-edit

      - name: Push changes
        run: git push

  build-windows:
    needs: update-and-build
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: "auto-update"

  build-linux:
    needs: update-and-build
    uses: ./.github/workflows/ci.yml